[package]
name = "miuu_replay"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.18"
rmpv = { version = "1.3.1", features = ["serde"] }
rmp-serde = "1.3.1"
csharp_binary_encoding = "0.4.0"
miniz_oxide = "0.9.0"
serde = { version = "1", features = ["derive"] }
